---
title: "Extended abstract"
output: html_document
---

This study seeks to answer two questions about the development of literacy  (reading competence) and numeracy (math competence) during adulthood: First, how stable are these skills in adulthood -- and if they change, does change involve gains or losses? Second, how is change distributed in the population and in demographic subgroups? To answer these questions, we used data from two German large-scale surveys: The PIAAC longitudinal study (PIAAC-L; *N* = 1,775) and the National Educational Panel Study (NEPS; *N* = 3,087). Both surveys offer repeated measures of adults' literacy and numeracy spaced three (PIAAC-L) to six (NEPS) years apart. We examine  mean-level change and ($\Delta{T_1,T_2}$) and rank-order consistencies ($r_{T_1,T_2}$) of skills in the total population as well as in sociodemographic subgroups defined by age, gender, and education. We used plausible values (PVs) to account for measurement error in skills. Results revealed that literacy and numeracy are highly but not perfectly stable over time. Rank-order consistencies ranged from *r* = .83 for literacy and *r* = 0.81 for numeracy over three years in PIAAC-L to *r* = .66  for literacy and *r* = .76 for numeracy over six years in NEPS, again with little variation across subgroups. Whereas mean-level change was near zero for both skills and in both studies, there was considerable variation in the change scores across individuals and, to a lesser extent, subgroups. Few  subgroup differences replicated across studies. We found some evidence for moderate skill gains during young adulthood (18--29 years) and losses in old age (55+ years), resembling age profiles from cross-sectional studies. This suggests that adults' literacy and numeracy are not set in stone and can change even over relatively short time periods. Our findings can serve as a benchmark against which to compare future longitudinal findings on stability and change in literacy and numeracy.